### PR TITLE
johncgenere's .cpp file with required output

### PR DESCRIPTION
**Pull request by johncgenere**
I added my .cpp file to src directory.

### CODE REVIEW

**Comment by stewartweiss** [comment]
@johncgenere :
Add proper documentation please. Minimally the program needs 

- authorship
- date of creation
- brief (one line) description
Then it is ready to be pulled.

**Comment by stewartweiss** [comment]
@johncgenere 
I am still waiting for a version with documentation.

**Review by johncgenere — COMMENTED** [review]
I added the author and date of creation along with a brief description.

**Comment by stewartweiss** [comment]
Requirements are now met.

**Pull request merged**
